version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/publish:
          orb-name: reflect/reflect-circleci-orb
          vcs-type: github
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *filters
